### ISSUE TITLE
zip END header error

### ISSUE THREAD

**Issue by pdelert** [gatling/frontline-maven-plugin#1]
I've been following the example of how to package gatling tests into .jar (https://gatling.io/docs/enterprise/cloud/reference/user/artifact_gen/#maven-project) 

I created a simple project with the necessary dependencies described in the link. While running 

`mvn clean package -DskipTests` I'm getting the following result:

`Execution default of goal io.gatling.frontline:frontline-maven-plugin:1.2.1:package failed: java.util.zip.ZipException: zip END header not found`

Mvn version: 
```
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_PL, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

Java version: 
```
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```

**Comment by slandelle** [comment]
This tool is only meant to be used by Gatling Enterprise/FrontLine customers.
Is it the case? If so, could you please tell me how you subscribed so I can route you to the proper support channel?

**Comment by slandelle** [comment]
my2cents: some dependency in the classpath is not a jar (zip) but something else, maybe some GraalVM tar.gz dep that should actually be in provided scope.

Still, if you're a Gatling Enterprise customer, please reach out through the proper support channel. Otherwise, please don't use this.
